
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-configmap
data:
  fluent-bit.conf: |
    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        Exclude_Path /var/log/containers/kindnet-*.log

    [OUTPUT]
        Name stdout
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit-deamonset
spec:
  selector:
    matchLabels:
      app: fluent-bit
  template:
    metadata:
      labels:
        app: fluent-bit
    spec:
      containers:
        - name: fluent-bit
          image: "cr.fluentbit.io/fluent/fluent-bit:3.2.2"
          volumeMounts:
            - name: config
              mountPath: /fluent-bit/etc
            - mountPath: /var/log
              name: varlog
            - mountPath: /var/lib/docker/containers
              name: varlibdockercontainers
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: fluent-bit-configmap
        - hostPath:
            path: /var/log
          name: varlog
        - hostPath:
            path: /var/lib/docker/containers
          name: varlibdockercontainers